export const LOGIN = 'LOGIN';
export const ADD_WALLET = 'ADD_WALLET';
export const LOGINAUTH = 'LOGINAUTH';
export const ORDER_LIST = 'ORDERLIST';
export const GET_ORDER = 'GET_ORDER';
export const FETCH_USER = 'AUTH_USER';
export const FEEDBACK = 'FEEDBACK';
export const CATEGORY = 'CAYEGORY';
export const CHEF = 'CHEF';
export const BLOG = 'BLOG';
export const DELETE_BLOG = 'DELETE_BLOG';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const DELETE_CHEF = 'DELETE_CHEF';
export const DELETE_RECIPE ='DELETE_RECIPE';
export const CLEARBLOG = 'CLEARBLOG';
export const CLEARREVIEW = 'CLEARReview';
export const CLEARCHEF = 'CLEARCHEF';
export const CLEARRECIPE = 'CLEARRECIPE';
export const CLEARFEEDBACK = 'CLEARFEEDBACK';
export const CLEARCATEGORY = 'CLEARCATEGORY';
export const CLEARORDER = 'CLEARORDER';
export const LOGOUT = 'LOGOUT'; 
export const CLOSERESPONSE = 'CLOSERESPONSE';
export const OPENRESPONSE = 'OPENRESPONSE';

export const SET_ENABLE_BACKGROUND_IMAGE = 'THEME_OPTIONS/SET_ENABLE_BACKGROUND_IMAGE';

export const SET_ENABLE_MOBILE_MENU = 'THEME_OPTIONS/SET_ENABLE_MOBILE_MENU';
export const SET_ENABLE_MOBILE_MENU_SMALL = 'THEME_OPTIONS/SET_ENABLE_MOBILE_MENU_SMALL';

export const SET_ENABLE_FIXED_HEADER = 'THEME_OPTIONS/SET_ENABLE_FIXED_HEADER';
export const SET_ENABLE_HEADER_SHADOW = 'THEME_OPTIONS/SET_ENABLE_HEADER_SHADOW';
export const SET_ENABLE_SIDEBAR_SHADOW = 'THEME_OPTIONS/SET_ENABLE_SIDEBAR_SHADOW';
export const SET_ENABLE_FIXED_SIDEBAR = 'THEME_OPTIONS/SET_ENABLE_FIXED_SIDEBAR';
export const SET_ENABLE_CLOSED_SIDEBAR = 'THEME_OPTIONS/SET_ENABLE_CLOSED_SIDEBAR';
export const SET_ENABLE_FIXED_FOOTER = 'THEME_OPTIONS/SET_ENABLE_FIXED_FOOTER';

export const SET_ENABLE_PAGETITLE_ICON = 'THEME_OPTIONS/SET_ENABLE_PAGETITLE_ICON';
export const SET_ENABLE_PAGETITLE_SUBHEADING = 'THEME_OPTIONS/SET_ENABLE_PAGETITLE_SUBHEADING';
export const SET_ENABLE_PAGE_TABS_ALT = 'THEME_OPTIONS/SET_ENABLE_PAGE_TABS_ALT';

export const SET_BACKGROUND_IMAGE = 'THEME_OPTIONS/SET_BACKGROUND_IMAGE';
export const SET_BACKGROUND_COLOR = 'THEME_OPTIONS/SET_BACKGROUND_COLOR';
export const SET_COLOR_SCHEME = 'THEME_OPTIONS/SET_COLOR_SCHEME';
export const SET_BACKGROUND_IMAGE_OPACITY = 'THEME_OPTIONS/SET_BACKGROUND_IMAGE_OPACITY';

export const SET_HEADER_BACKGROUND_COLOR = 'THEME_OPTIONS/SET_HEADER_BACKGROUND_COLOR';